global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'slurm'
    static_configs:
      - targets: ['slurm-exporter:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
